name: Astarte Device SDK Go end-to-end test

on:
  push:
  # Run on branch/tag creation
  create:
  # Run on pull requests
  pull_request:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Astarte Cluster
        id: setup-astarte
        uses: astarte-platform/astarte-cluster-action@v1
      - name: Install interfaces
        run: |
          astartectl realm-management interfaces sync ./e2e_tests/test/interfaces/*.json --non-interactive
          astartectl realm-management interfaces ls
      - name: Setup e2e env
        run: |
          DEVICE_ID=$(astartectl utils device-id generate-random)
          echo "E2E_DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
          CREDENTIALS_SECRET=$(astartectl pairing agent register --compact-output "$DEVICE_ID")
          echo "E2E_CREDENTIALS_SECRET=$CREDENTIALS_SECRET" >> $GITHUB_ENV
          JWT=$(astartectl utils gen-jwt all-realm-apis)
          echo "E2E_JWT=$JWT" >> $GITHUB_ENV
          echo "E2E_REALM=test" >> $GITHUB_ENV
          echo "E2E_ASTARTE_URL=https://api.autotest.astarte-platform.org" >> $GITHUB_ENV
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          # Ensure we're on Go 1.14
          go-version: '1.14.x'
      - name: Run test
        run: |
          echo $E2E_DEVICE_ID
          echo $E2E_CREDENTIALS_SECRET
          echo $E2E_JWT
          echo $E2E_REALM
          echo $E2E_ASTARTE_URL
          go test -v -timeout 20m -coverprofile=coverage.txt -covermode=atomic
        working-directory: ./e2e_tests 
        shell: bash
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
